/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bankingsys;

/**
 *
 * @author Jep
 */
public class loginPage extends javax.swing.JFrame {

    /**
     * Creates new form loginPage
     */
    public loginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Password = new javax.swing.JPasswordField();
        Email = new javax.swing.JTextField();
        SignIn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        BGimg = new javax.swing.JLabel();
        X_CloseWindow = new javax.swing.JLabel();
        Login = new javax.swing.JLabel();
        ForgotPass_Label1 = new javax.swing.JLabel();
        ForgotPass_Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Password.setBackground(new java.awt.Color(221, 238, 254));
        Password.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        Password.setForeground(new java.awt.Color(102, 102, 102));
        Password.setText("Paswword");
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        jPanel1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 190, 30));

        Email.setBackground(new java.awt.Color(221, 238, 254));
        Email.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        Email.setForeground(new java.awt.Color(102, 102, 102));
        Email.setText("Enter Email");
        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });
        jPanel1.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 190, 30));

        SignIn.setBackground(new java.awt.Color(102, 102, 255));
        SignIn.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        SignIn.setForeground(new java.awt.Color(255, 255, 255));
        SignIn.setText("Sign In");
        SignIn.setFocusable(false);
        SignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignInActionPerformed(evt);
            }
        });
        jPanel1.add(SignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, 160, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BGimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg BankingSYs.png"))); // NOI18N
        jPanel2.add(BGimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 410, 400));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 510));

        X_CloseWindow.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        X_CloseWindow.setText("   X");
        X_CloseWindow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                X_CloseWindowMouseClicked(evt);
            }
        });
        jPanel1.add(X_CloseWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 40, -1));

        Login.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        Login.setText("Login");
        jPanel1.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, 90, 40));

        ForgotPass_Label1.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        ForgotPass_Label1.setForeground(new java.awt.Color(153, 153, 153));
        ForgotPass_Label1.setText("Forgot Password?");
        jPanel1.add(ForgotPass_Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 260, -1, -1));

        ForgotPass_Label.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        ForgotPass_Label.setForeground(new java.awt.Color(153, 153, 153));
        ForgotPass_Label.setText("Create new account");
        jPanel1.add(ForgotPass_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignInActionPerformed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void X_CloseWindowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X_CloseWindowMouseClicked
        this.dispose();
    }//GEN-LAST:event_X_CloseWindowMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Flat Leaf".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BGimg;
    private javax.swing.JTextField Email;
    private javax.swing.JLabel ForgotPass_Label;
    private javax.swing.JLabel ForgotPass_Label1;
    private javax.swing.JLabel Login;
    private javax.swing.JPasswordField Password;
    private javax.swing.JButton SignIn;
    private javax.swing.JLabel X_CloseWindow;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
